-- MySQL Script generated by MySQL Workbench
-- Tue Aug 14 15:18:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hotel_management_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel_management_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_management_system` DEFAULT CHARACTER SET utf8 ;
USE `hotel_management_system` ;

-- -----------------------------------------------------
-- Table `hotel_management_system`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`countries` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`countries` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_management_system`.`hotel_chain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`hotel_chain` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`hotel_chain` (
  `chain_id` INT NOT NULL AUTO_INCREMENT,
  `chain_name` VARCHAR(45) NULL,
  PRIMARY KEY (`chain_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `chain_name_UNIQUE` ON `hotel_management_system`.`hotel_chain` (`chain_name` ASC);


-- -----------------------------------------------------
-- Table `hotel_management_system`.`star_rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`star_rating` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`star_rating` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `rating` BLOB NULL,
  PRIMARY KEY (`rating_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_management_system`.`discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`discounts` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`discounts` (
  `discount_id` INT NOT NULL AUTO_INCREMENT,
  `reason` VARCHAR(25) NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`discount_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_management_system`.`room_capacity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`room_capacity` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`room_capacity` (
  `roomcapacity_id` INT NOT NULL AUTO_INCREMENT,
  `capacity_name` VARCHAR(10) NOT NULL,
  `adults` INT NULL,
  `kids` INT NULL COMMENT 'Customer(\n	 CustomerID int primary key\n    ,CustomerName varchar(30)\n    ,SSID int\n    ,AddressLine1 varchar(20)\n    ,AddressLine2 varchar(20)\n    ,PhoneNUmber varchar(15)\n    ,Email varchar(20)\n    ,CheckIn datetime\n    ,CheckOut datetime\n    );',
  PRIMARY KEY (`roomcapacity_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_management_system`.`room_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`room_type` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`room_type` (
  `roomtype_id` INT NOT NULL AUTO_INCREMENT,
  `room_name` VARCHAR(25) NOT NULL,
  `numberof_beds` INT NOT NULL,
  `smoking_flag` TINYINT NULL,
  `room_capacity_roomcapacity_id` INT NOT NULL,
  PRIMARY KEY (`roomtype_id`, `room_capacity_roomcapacity_id`),
  CONSTRAINT `fk_room_type_room_capacity1`
    FOREIGN KEY (`room_capacity_roomcapacity_id`)
    REFERENCES `hotel_management_system`.`room_capacity` (`roomcapacity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_room_type_room_capacity1_idx` ON `hotel_management_system`.`room_type` (`room_capacity_roomcapacity_id` ASC);


-- -----------------------------------------------------
-- Table `hotel_management_system`.`room_features`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`room_features` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`room_features` (
  `feature_id` INT NOT NULL AUTO_INCREMENT,
  `feature_name` VARCHAR(25) NULL,
  `room_type_roomtype_id` INT NOT NULL,
  `room_type_room_capacity_roomcapacity_id` INT NOT NULL,
  PRIMARY KEY (`feature_id`, `room_type_roomtype_id`, `room_type_room_capacity_roomcapacity_id`),
  CONSTRAINT `fk_room_features_room_type1`
    FOREIGN KEY (`room_type_roomtype_id` , `room_type_room_capacity_roomcapacity_id`)
    REFERENCES `hotel_management_system`.`room_type` (`roomtype_id` , `room_capacity_roomcapacity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_room_features_room_type1_idx` ON `hotel_management_system`.`room_features` (`room_type_roomtype_id` ASC, `room_type_room_capacity_roomcapacity_id` ASC);


-- -----------------------------------------------------
-- Table `hotel_management_system`.`room_pricing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`room_pricing` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`room_pricing` (
  `roompricing_id` INT NOT NULL AUTO_INCREMENT,
  `price` DECIMAL(18,2) NULL,
  `discounts_discount_id` INT NOT NULL,
  `room_capacity_roomcapacity_id` INT NOT NULL,
  `room_features_feature_id` INT NOT NULL,
  PRIMARY KEY (`roompricing_id`, `discounts_discount_id`, `room_capacity_roomcapacity_id`, `room_features_feature_id`),
  CONSTRAINT `fk_room_pricing_discounts`
    FOREIGN KEY (`discounts_discount_id`)
    REFERENCES `hotel_management_system`.`discounts` (`discount_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_pricing_room_capacity1`
    FOREIGN KEY (`room_capacity_roomcapacity_id`)
    REFERENCES `hotel_management_system`.`room_capacity` (`roomcapacity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_pricing_room_features1`
    FOREIGN KEY (`room_features_feature_id`)
    REFERENCES `hotel_management_system`.`room_features` (`feature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_room_pricing_discounts_idx` ON `hotel_management_system`.`room_pricing` (`discounts_discount_id` ASC);

CREATE INDEX `fk_room_pricing_room_capacity1_idx` ON `hotel_management_system`.`room_pricing` (`room_capacity_roomcapacity_id` ASC);

CREATE INDEX `fk_room_pricing_room_features1_idx` ON `hotel_management_system`.`room_pricing` (`room_features_feature_id` ASC);


-- -----------------------------------------------------
-- Table `hotel_management_system`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`customer` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(25) NOT NULL,
  `SSID` INT NULL,
  `address_line1` VARCHAR(20) NOT NULL,
  `address_line2` VARCHAR(20) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  `check_in` DATETIME NULL,
  `check_out` DATETIME NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `phone_number_UNIQUE` ON `hotel_management_system`.`customer` (`phone_number` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `hotel_management_system`.`customer` (`email` ASC);


-- -----------------------------------------------------
-- Table `hotel_management_system`.`employee_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`employee_type` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`employee_type` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(20) NULL,
  PRIMARY KEY (`type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_management_system`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`address` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `addressline1` VARCHAR(20) NOT NULL,
  `addressline2` VARCHAR(20) NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `state` VARCHAR(20) NOT NULL,
  `country` VARCHAR(20) NOT NULL,
  `pincode` INT NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_management_system`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`rooms` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`rooms` (
  `rooms_id` INT NOT NULL AUTO_INCREMENT,
  `unit_number` VARCHAR(45) NOT NULL,
  `numberof_rooms` INT NOT NULL,
  `rooms_status` VARCHAR(10) NOT NULL,
  `room_type_roomtype_id` INT NOT NULL,
  `room_type_room_capacity_roomcapacity_id` INT NOT NULL,
  PRIMARY KEY (`rooms_id`, `room_type_roomtype_id`, `room_type_room_capacity_roomcapacity_id`),
  CONSTRAINT `fk_rooms_room_type1`
    FOREIGN KEY (`room_type_roomtype_id` , `room_type_room_capacity_roomcapacity_id`)
    REFERENCES `hotel_management_system`.`room_type` (`roomtype_id` , `room_capacity_roomcapacity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `unit_number_UNIQUE` ON `hotel_management_system`.`rooms` (`unit_number` ASC);

CREATE INDEX `fk_rooms_room_type1_idx` ON `hotel_management_system`.`rooms` (`room_type_roomtype_id` ASC, `room_type_room_capacity_roomcapacity_id` ASC);


-- -----------------------------------------------------
-- Table `hotel_management_system`.`hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`hotel` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`hotel` (
  `hotel_id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(100) NOT NULL,
  `description` VARCHAR(100) NULL,
  `floor_count` INT NOT NULL,
  `address_address_id` INT NOT NULL,
  `hotel_chain_chain_id` INT NOT NULL,
  `star_rating_rating_id` INT NOT NULL,
  `countries_country_id` INT NOT NULL,
  `room_capacity_roomcapacity_id` INT NOT NULL,
  PRIMARY KEY (`hotel_id`, `address_address_id`, `hotel_chain_chain_id`, `star_rating_rating_id`, `countries_country_id`, `room_capacity_roomcapacity_id`),
  CONSTRAINT `fk_hotel_address1`
    FOREIGN KEY (`address_address_id`)
    REFERENCES `hotel_management_system`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hotel_hotel_chain1`
    FOREIGN KEY (`hotel_chain_chain_id`)
    REFERENCES `hotel_management_system`.`hotel_chain` (`chain_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hotel_star_rating1`
    FOREIGN KEY (`star_rating_rating_id`)
    REFERENCES `hotel_management_system`.`star_rating` (`rating_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hotel_countries1`
    FOREIGN KEY (`countries_country_id`)
    REFERENCES `hotel_management_system`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hotel_room_capacity1`
    FOREIGN KEY (`room_capacity_roomcapacity_id`)
    REFERENCES `hotel_management_system`.`room_capacity` (`roomcapacity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_hotel_address1_idx` ON `hotel_management_system`.`hotel` (`address_address_id` ASC);

CREATE INDEX `fk_hotel_hotel_chain1_idx` ON `hotel_management_system`.`hotel` (`hotel_chain_chain_id` ASC);

CREATE INDEX `fk_hotel_star_rating1_idx` ON `hotel_management_system`.`hotel` (`star_rating_rating_id` ASC);

CREATE INDEX `fk_hotel_countries1_idx` ON `hotel_management_system`.`hotel` (`countries_country_id` ASC);

CREATE INDEX `fk_hotel_room_capacity1_idx` ON `hotel_management_system`.`hotel` (`room_capacity_roomcapacity_id` ASC);


-- -----------------------------------------------------
-- Table `hotel_management_system`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`employee` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(45) NOT NULL,
  `employee_email_address` VARCHAR(45) NOT NULL,
  `employee_type_type_id` INT NOT NULL,
  `hotel_hotel_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`, `employee_type_type_id`, `hotel_hotel_id`),
  CONSTRAINT `fk_employee_employee_type1`
    FOREIGN KEY (`employee_type_type_id`)
    REFERENCES `hotel_management_system`.`employee_type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_hotel1`
    FOREIGN KEY (`hotel_hotel_id`)
    REFERENCES `hotel_management_system`.`hotel` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `employee_email_address_UNIQUE` ON `hotel_management_system`.`employee` (`employee_email_address` ASC);

CREATE INDEX `fk_employee_employee_type1_idx` ON `hotel_management_system`.`employee` (`employee_type_type_id` ASC);

CREATE INDEX `fk_employee_hotel1_idx` ON `hotel_management_system`.`employee` (`hotel_hotel_id` ASC);


-- -----------------------------------------------------
-- Table `hotel_management_system`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`booking` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`booking` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `booking_date` DATETIME NOT NULL,
  `booking_type` VARCHAR(15) NULL,
  `booking_status` VARCHAR(25) NULL,
  `numberof_adults` INT NOT NULL,
  `children` INT NULL,
  `rooms_rooms_id` INT NOT NULL,
  `room_type_roomtype_id` INT NOT NULL,
  `customer_customer_id` INT NOT NULL,
  PRIMARY KEY (`booking_id`, `rooms_rooms_id`, `room_type_roomtype_id`, `customer_customer_id`),
  CONSTRAINT `fk_booking_rooms1`
    FOREIGN KEY (`rooms_rooms_id`)
    REFERENCES `hotel_management_system`.`rooms` (`rooms_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_room_type1`
    FOREIGN KEY (`room_type_roomtype_id`)
    REFERENCES `hotel_management_system`.`room_type` (`roomtype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_customer1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `hotel_management_system`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_booking_rooms1_idx` ON `hotel_management_system`.`booking` (`rooms_rooms_id` ASC);

CREATE INDEX `fk_booking_room_type1_idx` ON `hotel_management_system`.`booking` (`room_type_roomtype_id` ASC);

CREATE INDEX `fk_booking_customer1_idx` ON `hotel_management_system`.`booking` (`customer_customer_id` ASC);


-- -----------------------------------------------------
-- Table `hotel_management_system`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_management_system`.`inventory` ;

CREATE TABLE IF NOT EXISTS `hotel_management_system`.`inventory` (
  `inventory_id` INT NOT NULL AUTO_INCREMENT,
  `inventory_name` VARCHAR(25) NOT NULL,
  `quantity` INT NULL,
  `hotel_hotel_id` INT NOT NULL,
  PRIMARY KEY (`inventory_id`, `hotel_hotel_id`),
  CONSTRAINT `fk_inventory_hotel1`
    FOREIGN KEY (`hotel_hotel_id`)
    REFERENCES `hotel_management_system`.`hotel` (`hotel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_inventory_hotel1_idx` ON `hotel_management_system`.`inventory` (`hotel_hotel_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
